命令稿啟動於 2017年03月11日 (週六) 22時23分53秒
]0;xolovestephi@xolovestephi-VirtualBox: ~/lab1[01;32mxolovestephi@xolovestephi-VirtualBox[00m:[01;34m~/lab1[00m$ gi[K[Kg++ -o A A.cpp
]0;xolovestephi@xolovestephi-VirtualBox: ~/lab1[01;32mxolovestephi@xolovestephi-VirtualBox[00m:[01;34m~/lab1[00m$ ./A
22
22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1 ]0;xolovestephi@xolovestephi-VirtualBox: ~/lab1[01;32mxolovestephi@xolovestephi-VirtualBox[00m:[01;34m~/lab1[00m$ exit

命令稿已於 2017年03月11日 (週六) 22時24分13秒
 完成